name: Test
on:
  push:
jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      # with:
      #   nix_path: nixpkgs=channel:nixos-unstable
    - run: nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
    - run: nix-channel --update
    - run: nix-shell . -A install
